export const FETCH_ITEMS_REQUEST = "FETCH_ITEMS_REQUEST";
export const FETCH_ITEMS_SUCCESS = "FETCH_ITEMS_SUCCESS";
export const FETCH_ITEMS_FAILURE = "FETCH_ITEMS_FAILURE";

export const FETCH_ITEM_DETAILS_REQUEST = "FETCH_ITEM_DETAILS_REQUEST";
export const FETCH_ITEM_DETAILS_SUCCESS = "FETCH_ITEM_DETAILS_SUCCESS";
export const FETCH_ITEM_DETAILS_FAILURE = "FETCH_ITEM_DETAILS_FAILURE";
export const SET_SHOW_MODAL = "SET_SHOW_MODAL";

export const LOAD_MORE_ITEMS_REQUEST = "LOAD_MORE_ITEMS_REQUEST";
export const LOAD_MORE_ITEMS_SUCCESS = "LOAD_MORE_ITEMS_SUCCESS";
export const LOAD_MORE_ITEMS_FAILURE = "LOAD_MORE_ITEMS_FAILURE";
